### ISSUE TITLE
A9G giving fixed location (of hongkong)

### ISSUE THREAD

**Issue by fu-techiot** [Ai-Thinker-Open/GPRS_C_SDK#181]
**Hello There,**
A9g pudding board stuck at giving **FIXED LOCATION** 
I just want to know this issue is related to Hardware or Software?

or is this because of damaged antenna ?

**Comment by Neutree** [comment]
check NMEA or demo output if  fixed? fix mode should >=2

**Comment by fu-techiot** [comment]
yes, @Neutree actually that's what I wanna ask.

I'm always getting GPS data with **GPS FIX MODE:1** AND BDS FIX ** MODE: 1** I already read other Issues.:)
that's why I'm asking is there any problem of CODE or Hardware or antenna?

here is the data of one A9G pudding Hardware, this remains always the same(HONGKONG city location).
`GPS fix mode:1, BDS fix mode:1, fix quality:0, satellites tracked:0, GPS sates total:0, is fixed:no fix, coordinate:WGS84, Latitude:22.606128, Longitude:113.839978, unit:degree,altitude:0.000000`

and this one is another hardware OUTPUT this also remains the same.

 `GPS fix mode:1, BDS fix mode:1, fix quality:0, satellites tracked:0, gps sates total:0, is fixed:no fix, coordinate:WGS84, Latitude:23.194863, Longitude:72.637818, unit:degree,altitude:0.000000`

so can you please tell me what is the issue?

**Comment by Neutree** [comment]
the log shows us the module didn't fix, means the latitude and longitude is invalid,

please place you antenna in open area and try again

And you can show your board and antenna here with picture, it's more helpful for us to resolve it

**Comment by updesh31** [comment]
yes fix quality:0 means GPS is not locked so it's giving invalid lat/lon. My device is working perfectly even with passive GPS antenna. fu-techiot I think there is a problem with antenna.

**Comment by fu-techiot** [comment]
**thank you ** @Neutree @updesh31 For your quick response,

yes, I'm able to get proper GPS Location in OPEN area, I think there are a power issue and connection issues.

**Comment by martinconstante** [comment]
I had the same problem, I solved it with an external power supply and put the antenna outside the window. 
martin.constante@gmail.com

**Comment by enggsajjad** [comment]
i have the same issue. does it compulsory to place the antenna in window or under open sky?
If we have the antenna inside the room, can we not get the updated the GPS coordinated?
How this antenna function is different than the working of a cellphone GPS.

**Comment by ZakKemble** [comment]
If you have to stick a GPS antenna outside of your window to get a signal then yes, that is compulsory in your case.

Phones use other sources of information to get your location, like cell towers and nearby WiFi access points. Use an app like [GPS Status](https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2) to see how many GPS satellites your phone can really see and lock on to.

**Comment by JazminFerre** [comment]
> If you have to stick a GPS antenna outside of your window to get a signal then yes, that is compulsory in your case.
> 
> Phones use other sources of information to get your location, like cell towers and nearby WiFi access points. Use an app like [GPS Status](https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2) to see how many GPS satellites your phone can really see and lock on to.

Is there something that I can program in the module to know the information about the nearest cell towers?
